### ISSUE TITLE
Strange interaction between 'if await' and 'config(handling='one')'

### ISSUE THREAD

**Issue by AlexisGrall** [DistAlgo/distalgo#14]
When there is a yield point inside an 'if await' statement, two messages are potentially handled instead of one (as expected with config(handling='one')).
Here is an example.

```python
-- toto
if await(cond):
        # no messages handled yet
        -- rcv # two messages are handled here.
```

Here is a more detailed example.
[handlingone.txt](https://github.com/DistAlgo/distalgo/files/2111084/handlingone.txt)

**Comment by yanhongliu** [comment]
Hi, you should not use "rcv" as both a label/yield point name and a field name.  if you change the label name at "-- rcv" and at "at (rcv,)" to, say, "test", you should see the expected result. 
thanks for reporting.  we will try to give a warning for that.

**Comment by AlexisGrall** [comment]
I changed the label "rcv" to "test" as suggested and I still get the same problem.
[handlingone.txt](https://github.com/DistAlgo/distalgo/files/2114254/handlingone.txt)

**Comment by AlexisGrall** [comment]
It seems to happen because of the first yield point.
On the first 'toto' yield point, no messages are received and it will cause the next yield point to be able to handle two messages instead of one.
I simplified the example since it has nothing to do with 'if await' but only with yield points.
[test.txt](https://github.com/DistAlgo/distalgo/files/2114555/test.txt)

**Comment by yanhongliu** [comment]
Hi, it turns out there is a bug in the implementation (my "fix" yesterday
worked because I also changed "work" to something simpler, not waiting a
random long time).  The bug is that another msg could be put in the job
queue at the previous yield point (if there is enough time to receive a msg
there), even though only one msg is put in the queue at this yield point,
and both jobs got run at this yield point (the first msg wasn't handled in
the previous yield point because it didn't match the label for that yield
point).

We will have to fix this in the next release.  For now, you could remove
the previous yield point, or make sure that messages received earlier are
handled earlier.  This is not sufficient for all cases though.

Thanks again for reporting this.  We've not found a real use of handling
"one" ourselves, even though we were prepared to add more options---2 or
more, for example :)   I wonder why you need to use it.

**Comment by AlexisGrall** [comment]
I am working on modeling distributed algorithms in [event-b](http://wiki.event-b.org/index.php/Main_Page) and I want to make a bridge from event-b models into some executable programs. I chose to try with DistAlgo since the language is high level and closer to event-b.
I thus have to find a way to model the DistAlgo semantics in event-b and to find a DistAlgo pattern which would translate an event-b machine.

The issue I have now is that the operational semantics described in the annex of  the article you wrote with your colleagues and the implementation are not the same for the reception of messages.

In the semantics, all (or only the first if handling=one) messages in the message queue are handled at a yield point and for each of these messages a corresponding receive method is executed if there is one, else skip. Moreover, the handled messages (all of them if handling=all and only the first if handling=one) are removed from the message queue.

In the python implementation, it doesn't work like this. If a message has been handled at a previous yield point with no matching receive method, a matching receive method for this message can still be executed at a later yield point. Therefore, a message can be in the received sequence, but the corresponding message handler can be called a long time after.

This is the article where I found the semantics :
Liu, Y. A., Stoller, S. D., & Lin, B. (2017). From clarity to efficiency for distributed algorithms. ACM Transactions on Programming Languages and Systems (TOPLAS), 39(3), 12.

**Comment by sadboy** [comment]
Hi, this should now be fix on master, thanks for reporting!

**Comment by yanhongliu** [comment]
It's great you are bridging from event-b into DistAlgo for executable
distributed programs! We of course think DistAlgo is best for writing
executable distributed programs, at any level. :)

You then say "I thus have to find a way to model the DistAlgo semantics in
event-b", which I think sounds backwards, as I'd think you need to find a
way to model event-b machines in DistAlgo, which should be easy in all
cases because DistAlgo is powerful.

In particular, you can easily program at two extreme levels and all kinds
of combinations in between:

at the highest level, all or almost all synchronization can be done using
await on "received" (and what and when receive-definitions run shouldn't
really matter, at least not in good distributed algorithms we've seen).

at the lowest level, you just write a single receive-definition that
matches all messages and you handle all msgs one at a time, as in standard
event-driven programming (and there is no need to use await on "received"
at all).

just in case you have any practical distributed algorithms that you have
trouble expressing, please feel free to let us know.  let us know if you
still see handling issues too.   thanks!
